/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.records;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;
import com.datatable.repository.tables.DtApp;
import com.datatable.repository.tables.interfaces.IDtApp;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * app
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtAppRecord extends UpdatableRecordImpl<DtAppRecord> implements VertxPojo, Record9<Long, LocalDateTime, LocalDateTime, String, String, Long, Long, Short, Long>, IDtApp {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dt_app.id</code>.
     */
    @Override
    public DtAppRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.dt_app.gmt_create</code>. 创建时间
     */
    @Override
    public DtAppRecord setGmtCreate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.gmt_create</code>. 创建时间
     */
    @Override
    public LocalDateTime getGmtCreate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.dt_app.gmt_modified</code>. 更新时间
     */
    @Override
    public DtAppRecord setGmtModified(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.gmt_modified</code>. 更新时间
     */
    @Override
    public LocalDateTime getGmtModified() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.dt_app.app_name</code>. 应用名称
     */
    @Override
    public DtAppRecord setAppName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.app_name</code>. 应用名称
     */
    @Override
    public String getAppName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.dt_app.app_desc</code>. 应用描述
     */
    @Override
    public DtAppRecord setAppDesc(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.app_desc</code>. 应用描述
     */
    @Override
    public String getAppDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.dt_app.creator</code>. 创建人
     */
    @Override
    public DtAppRecord setCreator(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.creator</code>. 创建人
     */
    @Override
    public Long getCreator() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.dt_app.editor</code>. 更新人
     */
    @Override
    public DtAppRecord setEditor(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.editor</code>. 更新人
     */
    @Override
    public Long getEditor() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.dt_app.is_delete</code>. 0 否 1 是
     */
    @Override
    public DtAppRecord setIsDelete(Short value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.is_delete</code>. 0 否 1 是
     */
    @Override
    public Short getIsDelete() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.dt_app.tenant_id</code>. 租户id
     */
    @Override
    public DtAppRecord setTenantId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_app.tenant_id</code>. 租户id
     */
    @Override
    public Long getTenantId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, LocalDateTime, LocalDateTime, String, String, Long, Long, Short, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, LocalDateTime, LocalDateTime, String, String, Long, Long, Short, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DtApp.DT_APP.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return DtApp.DT_APP.GMT_CREATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return DtApp.DT_APP.GMT_MODIFIED;
    }

    @Override
    public Field<String> field4() {
        return DtApp.DT_APP.APP_NAME;
    }

    @Override
    public Field<String> field5() {
        return DtApp.DT_APP.APP_DESC;
    }

    @Override
    public Field<Long> field6() {
        return DtApp.DT_APP.CREATOR;
    }

    @Override
    public Field<Long> field7() {
        return DtApp.DT_APP.EDITOR;
    }

    @Override
    public Field<Short> field8() {
        return DtApp.DT_APP.IS_DELETE;
    }

    @Override
    public Field<Long> field9() {
        return DtApp.DT_APP.TENANT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime component3() {
        return getGmtModified();
    }

    @Override
    public String component4() {
        return getAppName();
    }

    @Override
    public String component5() {
        return getAppDesc();
    }

    @Override
    public Long component6() {
        return getCreator();
    }

    @Override
    public Long component7() {
        return getEditor();
    }

    @Override
    public Short component8() {
        return getIsDelete();
    }

    @Override
    public Long component9() {
        return getTenantId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime value3() {
        return getGmtModified();
    }

    @Override
    public String value4() {
        return getAppName();
    }

    @Override
    public String value5() {
        return getAppDesc();
    }

    @Override
    public Long value6() {
        return getCreator();
    }

    @Override
    public Long value7() {
        return getEditor();
    }

    @Override
    public Short value8() {
        return getIsDelete();
    }

    @Override
    public Long value9() {
        return getTenantId();
    }

    @Override
    public DtAppRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DtAppRecord value2(LocalDateTime value) {
        setGmtCreate(value);
        return this;
    }

    @Override
    public DtAppRecord value3(LocalDateTime value) {
        setGmtModified(value);
        return this;
    }

    @Override
    public DtAppRecord value4(String value) {
        setAppName(value);
        return this;
    }

    @Override
    public DtAppRecord value5(String value) {
        setAppDesc(value);
        return this;
    }

    @Override
    public DtAppRecord value6(Long value) {
        setCreator(value);
        return this;
    }

    @Override
    public DtAppRecord value7(Long value) {
        setEditor(value);
        return this;
    }

    @Override
    public DtAppRecord value8(Short value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public DtAppRecord value9(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public DtAppRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, Long value6, Long value7, Short value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDtApp from) {
        setId(from.getId());
        setGmtCreate(from.getGmtCreate());
        setGmtModified(from.getGmtModified());
        setAppName(from.getAppName());
        setAppDesc(from.getAppDesc());
        setCreator(from.getCreator());
        setEditor(from.getEditor());
        setIsDelete(from.getIsDelete());
        setTenantId(from.getTenantId());
    }

    @Override
    public <E extends IDtApp> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DtAppRecord
     */
    public DtAppRecord() {
        super(DtApp.DT_APP);
    }

    /**
     * Create a detached, initialised DtAppRecord
     */
    public DtAppRecord(Long id, LocalDateTime gmtCreate, LocalDateTime gmtModified, String appName, String appDesc, Long creator, Long editor, Short isDelete, Long tenantId) {
        super(DtApp.DT_APP);

        setId(id);
        setGmtCreate(gmtCreate);
        setGmtModified(gmtModified);
        setAppName(appName);
        setAppDesc(appDesc);
        setCreator(creator);
        setEditor(editor);
        setIsDelete(isDelete);
        setTenantId(tenantId);
    }

    /**
     * Create a detached, initialised DtAppRecord
     */
    public DtAppRecord(com.datatable.repository.tables.pojos.DtApp value) {
        super(DtApp.DT_APP);

        if (value != null) {
            setId(value.getId());
            setGmtCreate(value.getGmtCreate());
            setGmtModified(value.getGmtModified());
            setAppName(value.getAppName());
            setAppDesc(value.getAppDesc());
            setCreator(value.getCreator());
            setEditor(value.getEditor());
            setIsDelete(value.getIsDelete());
            setTenantId(value.getTenantId());
        }
    }

        public DtAppRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
