/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.records;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;
import com.datatable.repository.tables.DtField;
import com.datatable.repository.tables.interfaces.IDtField;

import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 字段信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtFieldRecord extends UpdatableRecordImpl<DtFieldRecord> implements VertxPojo, Record13<Long, LocalDateTime, LocalDateTime, Long, Long, String, String, String, JsonObject, Short, Long, Long, Long>, IDtField {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dt_field.id</code>.
     */
    @Override
    public DtFieldRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.dt_field.gmt_create</code>. 创建时间
     */
    @Override
    public DtFieldRecord setGmtCreate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.gmt_create</code>. 创建时间
     */
    @Override
    public LocalDateTime getGmtCreate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.dt_field.gmt_modified</code>. 修改时间
     */
    @Override
    public DtFieldRecord setGmtModified(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.gmt_modified</code>. 修改时间
     */
    @Override
    public LocalDateTime getGmtModified() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.dt_field.creator</code>. 创建人
     */
    @Override
    public DtFieldRecord setCreator(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.creator</code>. 创建人
     */
    @Override
    public Long getCreator() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.dt_field.editor</code>. 更新人
     */
    @Override
    public DtFieldRecord setEditor(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.editor</code>. 更新人
     */
    @Override
    public Long getEditor() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.dt_field.field_name</code>. 字段名称
     */
    @Override
    public DtFieldRecord setFieldName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.field_name</code>. 字段名称
     */
    @Override
    public String getFieldName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.dt_field.field_desc</code>. 字段描述
     */
    @Override
    public DtFieldRecord setFieldDesc(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.field_desc</code>. 字段描述
     */
    @Override
    public String getFieldDesc() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.dt_field.field_type</code>. 字段类型
     */
    @Override
    public DtFieldRecord setFieldType(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.field_type</code>. 字段类型
     */
    @Override
    public String getFieldType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.dt_field.field_property</code>. 字段属性
     */
    @Override
    public DtFieldRecord setFieldProperty(JsonObject value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.field_property</code>. 字段属性
     */
    @Override
    public JsonObject getFieldProperty() {
        return (JsonObject) get(8);
    }

    /**
     * Setter for <code>public.dt_field.is_delete</code>. 0 否 1 是
     */
    @Override
    public DtFieldRecord setIsDelete(Short value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.is_delete</code>. 0 否 1 是
     */
    @Override
    public Short getIsDelete() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>public.dt_field.tenant_id</code>. 租户id
     */
    @Override
    public DtFieldRecord setTenantId(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.tenant_id</code>. 租户id
     */
    @Override
    public Long getTenantId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.dt_field.app_id</code>. 应用id
     */
    @Override
    public DtFieldRecord setAppId(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.app_id</code>. 应用id
     */
    @Override
    public Long getAppId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.dt_field.template_id</code>. 模版id
     */
    @Override
    public DtFieldRecord setTemplateId(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_field.template_id</code>. 模版id
     */
    @Override
    public Long getTemplateId() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, LocalDateTime, LocalDateTime, Long, Long, String, String, String, JsonObject, Short, Long, Long, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, LocalDateTime, LocalDateTime, Long, Long, String, String, String, JsonObject, Short, Long, Long, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DtField.DT_FIELD.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return DtField.DT_FIELD.GMT_CREATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return DtField.DT_FIELD.GMT_MODIFIED;
    }

    @Override
    public Field<Long> field4() {
        return DtField.DT_FIELD.CREATOR;
    }

    @Override
    public Field<Long> field5() {
        return DtField.DT_FIELD.EDITOR;
    }

    @Override
    public Field<String> field6() {
        return DtField.DT_FIELD.FIELD_NAME;
    }

    @Override
    public Field<String> field7() {
        return DtField.DT_FIELD.FIELD_DESC;
    }

    @Override
    public Field<String> field8() {
        return DtField.DT_FIELD.FIELD_TYPE;
    }

    @Override
    public Field<JsonObject> field9() {
        return DtField.DT_FIELD.FIELD_PROPERTY;
    }

    @Override
    public Field<Short> field10() {
        return DtField.DT_FIELD.IS_DELETE;
    }

    @Override
    public Field<Long> field11() {
        return DtField.DT_FIELD.TENANT_ID;
    }

    @Override
    public Field<Long> field12() {
        return DtField.DT_FIELD.APP_ID;
    }

    @Override
    public Field<Long> field13() {
        return DtField.DT_FIELD.TEMPLATE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime component3() {
        return getGmtModified();
    }

    @Override
    public Long component4() {
        return getCreator();
    }

    @Override
    public Long component5() {
        return getEditor();
    }

    @Override
    public String component6() {
        return getFieldName();
    }

    @Override
    public String component7() {
        return getFieldDesc();
    }

    @Override
    public String component8() {
        return getFieldType();
    }

    @Override
    public JsonObject component9() {
        return getFieldProperty();
    }

    @Override
    public Short component10() {
        return getIsDelete();
    }

    @Override
    public Long component11() {
        return getTenantId();
    }

    @Override
    public Long component12() {
        return getAppId();
    }

    @Override
    public Long component13() {
        return getTemplateId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime value3() {
        return getGmtModified();
    }

    @Override
    public Long value4() {
        return getCreator();
    }

    @Override
    public Long value5() {
        return getEditor();
    }

    @Override
    public String value6() {
        return getFieldName();
    }

    @Override
    public String value7() {
        return getFieldDesc();
    }

    @Override
    public String value8() {
        return getFieldType();
    }

    @Override
    public JsonObject value9() {
        return getFieldProperty();
    }

    @Override
    public Short value10() {
        return getIsDelete();
    }

    @Override
    public Long value11() {
        return getTenantId();
    }

    @Override
    public Long value12() {
        return getAppId();
    }

    @Override
    public Long value13() {
        return getTemplateId();
    }

    @Override
    public DtFieldRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DtFieldRecord value2(LocalDateTime value) {
        setGmtCreate(value);
        return this;
    }

    @Override
    public DtFieldRecord value3(LocalDateTime value) {
        setGmtModified(value);
        return this;
    }

    @Override
    public DtFieldRecord value4(Long value) {
        setCreator(value);
        return this;
    }

    @Override
    public DtFieldRecord value5(Long value) {
        setEditor(value);
        return this;
    }

    @Override
    public DtFieldRecord value6(String value) {
        setFieldName(value);
        return this;
    }

    @Override
    public DtFieldRecord value7(String value) {
        setFieldDesc(value);
        return this;
    }

    @Override
    public DtFieldRecord value8(String value) {
        setFieldType(value);
        return this;
    }

    @Override
    public DtFieldRecord value9(JsonObject value) {
        setFieldProperty(value);
        return this;
    }

    @Override
    public DtFieldRecord value10(Short value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public DtFieldRecord value11(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public DtFieldRecord value12(Long value) {
        setAppId(value);
        return this;
    }

    @Override
    public DtFieldRecord value13(Long value) {
        setTemplateId(value);
        return this;
    }

    @Override
    public DtFieldRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, Long value4, Long value5, String value6, String value7, String value8, JsonObject value9, Short value10, Long value11, Long value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDtField from) {
        setId(from.getId());
        setGmtCreate(from.getGmtCreate());
        setGmtModified(from.getGmtModified());
        setCreator(from.getCreator());
        setEditor(from.getEditor());
        setFieldName(from.getFieldName());
        setFieldDesc(from.getFieldDesc());
        setFieldType(from.getFieldType());
        setFieldProperty(from.getFieldProperty());
        setIsDelete(from.getIsDelete());
        setTenantId(from.getTenantId());
        setAppId(from.getAppId());
        setTemplateId(from.getTemplateId());
    }

    @Override
    public <E extends IDtField> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DtFieldRecord
     */
    public DtFieldRecord() {
        super(DtField.DT_FIELD);
    }

    /**
     * Create a detached, initialised DtFieldRecord
     */
    public DtFieldRecord(Long id, LocalDateTime gmtCreate, LocalDateTime gmtModified, Long creator, Long editor, String fieldName, String fieldDesc, String fieldType, JsonObject fieldProperty, Short isDelete, Long tenantId, Long appId, Long templateId) {
        super(DtField.DT_FIELD);

        setId(id);
        setGmtCreate(gmtCreate);
        setGmtModified(gmtModified);
        setCreator(creator);
        setEditor(editor);
        setFieldName(fieldName);
        setFieldDesc(fieldDesc);
        setFieldType(fieldType);
        setFieldProperty(fieldProperty);
        setIsDelete(isDelete);
        setTenantId(tenantId);
        setAppId(appId);
        setTemplateId(templateId);
    }

    /**
     * Create a detached, initialised DtFieldRecord
     */
    public DtFieldRecord(com.datatable.repository.tables.pojos.DtField value) {
        super(DtField.DT_FIELD);

        if (value != null) {
            setId(value.getId());
            setGmtCreate(value.getGmtCreate());
            setGmtModified(value.getGmtModified());
            setCreator(value.getCreator());
            setEditor(value.getEditor());
            setFieldName(value.getFieldName());
            setFieldDesc(value.getFieldDesc());
            setFieldType(value.getFieldType());
            setFieldProperty(value.getFieldProperty());
            setIsDelete(value.getIsDelete());
            setTenantId(value.getTenantId());
            setAppId(value.getAppId());
            setTemplateId(value.getTemplateId());
        }
    }

        public DtFieldRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
