/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.records;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;
import com.datatable.repository.tables.DtUser;
import com.datatable.repository.tables.interfaces.IDtUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtUserRecord extends UpdatableRecordImpl<DtUserRecord> implements VertxPojo, Record10<Long, Long, Long, String, String, String, String, Short, Long, Long>, IDtUser {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dt_user.id</code>.
     */
    @Override
    public DtUserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.dt_user.gmt_create</code>. 创建时间
     */
    @Override
    public DtUserRecord setGmtCreate(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.gmt_create</code>. 创建时间
     */
    @Override
    public Long getGmtCreate() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.dt_user.gmt_modified</code>. 修改时间
     */
    @Override
    public DtUserRecord setGmtModified(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.gmt_modified</code>. 修改时间
     */
    @Override
    public Long getGmtModified() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.dt_user.user_name</code>. 用户名
     */
    @Override
    public DtUserRecord setUserName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.user_name</code>. 用户名
     */
    @Override
    public String getUserName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.dt_user.user_account</code>. 账号
     */
    @Override
    public DtUserRecord setUserAccount(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.user_account</code>. 账号
     */
    @Override
    public String getUserAccount() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.dt_user.user_password</code>. 密码
     */
    @Override
    public DtUserRecord setUserPassword(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.user_password</code>. 密码
     */
    @Override
    public String getUserPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.dt_user.user_status</code>. 用户状态
     */
    @Override
    public DtUserRecord setUserStatus(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.user_status</code>. 用户状态
     */
    @Override
    public String getUserStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.dt_user.is_delete</code>. 0 否 1 是
     */
    @Override
    public DtUserRecord setIsDelete(Short value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.is_delete</code>. 0 否 1 是
     */
    @Override
    public Short getIsDelete() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.dt_user.tenant_id</code>. 租户id
     */
    @Override
    public DtUserRecord setTenantId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.tenant_id</code>. 租户id
     */
    @Override
    public Long getTenantId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.dt_user.app_id</code>. 应用id
     */
    @Override
    public DtUserRecord setAppId(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.dt_user.app_id</code>. 应用id
     */
    @Override
    public Long getAppId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Long, String, String, String, String, Short, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, Long, String, String, String, String, Short, Long, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DtUser.DT_USER.ID;
    }

    @Override
    public Field<Long> field2() {
        return DtUser.DT_USER.GMT_CREATE;
    }

    @Override
    public Field<Long> field3() {
        return DtUser.DT_USER.GMT_MODIFIED;
    }

    @Override
    public Field<String> field4() {
        return DtUser.DT_USER.USER_NAME;
    }

    @Override
    public Field<String> field5() {
        return DtUser.DT_USER.USER_ACCOUNT;
    }

    @Override
    public Field<String> field6() {
        return DtUser.DT_USER.USER_PASSWORD;
    }

    @Override
    public Field<String> field7() {
        return DtUser.DT_USER.USER_STATUS;
    }

    @Override
    public Field<Short> field8() {
        return DtUser.DT_USER.IS_DELETE;
    }

    @Override
    public Field<Long> field9() {
        return DtUser.DT_USER.TENANT_ID;
    }

    @Override
    public Field<Long> field10() {
        return DtUser.DT_USER.APP_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGmtCreate();
    }

    @Override
    public Long component3() {
        return getGmtModified();
    }

    @Override
    public String component4() {
        return getUserName();
    }

    @Override
    public String component5() {
        return getUserAccount();
    }

    @Override
    public String component6() {
        return getUserPassword();
    }

    @Override
    public String component7() {
        return getUserStatus();
    }

    @Override
    public Short component8() {
        return getIsDelete();
    }

    @Override
    public Long component9() {
        return getTenantId();
    }

    @Override
    public Long component10() {
        return getAppId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGmtCreate();
    }

    @Override
    public Long value3() {
        return getGmtModified();
    }

    @Override
    public String value4() {
        return getUserName();
    }

    @Override
    public String value5() {
        return getUserAccount();
    }

    @Override
    public String value6() {
        return getUserPassword();
    }

    @Override
    public String value7() {
        return getUserStatus();
    }

    @Override
    public Short value8() {
        return getIsDelete();
    }

    @Override
    public Long value9() {
        return getTenantId();
    }

    @Override
    public Long value10() {
        return getAppId();
    }

    @Override
    public DtUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DtUserRecord value2(Long value) {
        setGmtCreate(value);
        return this;
    }

    @Override
    public DtUserRecord value3(Long value) {
        setGmtModified(value);
        return this;
    }

    @Override
    public DtUserRecord value4(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public DtUserRecord value5(String value) {
        setUserAccount(value);
        return this;
    }

    @Override
    public DtUserRecord value6(String value) {
        setUserPassword(value);
        return this;
    }

    @Override
    public DtUserRecord value7(String value) {
        setUserStatus(value);
        return this;
    }

    @Override
    public DtUserRecord value8(Short value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public DtUserRecord value9(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public DtUserRecord value10(Long value) {
        setAppId(value);
        return this;
    }

    @Override
    public DtUserRecord values(Long value1, Long value2, Long value3, String value4, String value5, String value6, String value7, Short value8, Long value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDtUser from) {
        setId(from.getId());
        setGmtCreate(from.getGmtCreate());
        setGmtModified(from.getGmtModified());
        setUserName(from.getUserName());
        setUserAccount(from.getUserAccount());
        setUserPassword(from.getUserPassword());
        setUserStatus(from.getUserStatus());
        setIsDelete(from.getIsDelete());
        setTenantId(from.getTenantId());
        setAppId(from.getAppId());
    }

    @Override
    public <E extends IDtUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DtUserRecord
     */
    public DtUserRecord() {
        super(DtUser.DT_USER);
    }

    /**
     * Create a detached, initialised DtUserRecord
     */
    public DtUserRecord(Long id, Long gmtCreate, Long gmtModified, String userName, String userAccount, String userPassword, String userStatus, Short isDelete, Long tenantId, Long appId) {
        super(DtUser.DT_USER);

        setId(id);
        setGmtCreate(gmtCreate);
        setGmtModified(gmtModified);
        setUserName(userName);
        setUserAccount(userAccount);
        setUserPassword(userPassword);
        setUserStatus(userStatus);
        setIsDelete(isDelete);
        setTenantId(tenantId);
        setAppId(appId);
    }

    /**
     * Create a detached, initialised DtUserRecord
     */
    public DtUserRecord(com.datatable.repository.tables.pojos.DtUser value) {
        super(DtUser.DT_USER);

        if (value != null) {
            setId(value.getId());
            setGmtCreate(value.getGmtCreate());
            setGmtModified(value.getGmtModified());
            setUserName(value.getUserName());
            setUserAccount(value.getUserAccount());
            setUserPassword(value.getUserPassword());
            setUserStatus(value.getUserStatus());
            setIsDelete(value.getIsDelete());
            setTenantId(value.getTenantId());
            setAppId(value.getAppId());
        }
    }

        public DtUserRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
