/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables;


import com.datatable.framework.plugin.jooq.shared.ObjectToJsonObjectBinding;
import com.datatable.repository.Indexes;
import com.datatable.repository.Keys;
import com.datatable.repository.Public;
import com.datatable.repository.tables.records.DtFieldRecord;

import io.vertx.core.json.JsonObject;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 字段信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtField extends TableImpl<DtFieldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.dt_field</code>
     */
    public static final DtField DT_FIELD = new DtField();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DtFieldRecord> getRecordType() {
        return DtFieldRecord.class;
    }

    /**
     * The column <code>public.dt_field.id</code>.
     */
    public final TableField<DtFieldRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.dt_field.gmt_create</code>. 创建时间
     */
    public final TableField<DtFieldRecord, LocalDateTime> GMT_CREATE = createField(DSL.name("gmt_create"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "创建时间");

    /**
     * The column <code>public.dt_field.gmt_modified</code>. 修改时间
     */
    public final TableField<DtFieldRecord, LocalDateTime> GMT_MODIFIED = createField(DSL.name("gmt_modified"), SQLDataType.LOCALDATETIME(6), this, "修改时间");

    /**
     * The column <code>public.dt_field.creator</code>. 创建人
     */
    public final TableField<DtFieldRecord, Long> CREATOR = createField(DSL.name("creator"), SQLDataType.BIGINT.nullable(false), this, "创建人");

    /**
     * The column <code>public.dt_field.editor</code>. 更新人
     */
    public final TableField<DtFieldRecord, Long> EDITOR = createField(DSL.name("editor"), SQLDataType.BIGINT, this, "更新人");

    /**
     * The column <code>public.dt_field.field_name</code>. 字段名称
     */
    public final TableField<DtFieldRecord, String> FIELD_NAME = createField(DSL.name("field_name"), SQLDataType.VARCHAR(50).nullable(false), this, "字段名称");

    /**
     * The column <code>public.dt_field.field_desc</code>. 字段描述
     */
    public final TableField<DtFieldRecord, String> FIELD_DESC = createField(DSL.name("field_desc"), SQLDataType.VARCHAR(255), this, "字段描述");

    /**
     * The column <code>public.dt_field.field_type</code>. 字段类型
     */
    public final TableField<DtFieldRecord, String> FIELD_TYPE = createField(DSL.name("field_type"), SQLDataType.VARCHAR(30).nullable(false), this, "字段类型");

    /**
     * The column <code>public.dt_field.field_property</code>. 字段属性
     */
    public final TableField<DtFieldRecord, JsonObject> FIELD_PROPERTY = createField(DSL.name("field_property"), SQLDataType.JSONB, this, "字段属性", new ObjectToJsonObjectBinding());

    /**
     * The column <code>public.dt_field.is_delete</code>. 0 否 1 是
     */
    public final TableField<DtFieldRecord, Short> IS_DELETE = createField(DSL.name("is_delete"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field("0", SQLDataType.SMALLINT)), this, "0 否 1 是");

    /**
     * The column <code>public.dt_field.tenant_id</code>. 租户id
     */
    public final TableField<DtFieldRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id");

    /**
     * The column <code>public.dt_field.app_id</code>. 应用id
     */
    public final TableField<DtFieldRecord, Long> APP_ID = createField(DSL.name("app_id"), SQLDataType.BIGINT.nullable(false), this, "应用id");

    /**
     * The column <code>public.dt_field.template_id</code>. 模版id
     */
    public final TableField<DtFieldRecord, Long> TEMPLATE_ID = createField(DSL.name("template_id"), SQLDataType.BIGINT.nullable(false), this, "模版id");

    private DtField(Name alias, Table<DtFieldRecord> aliased) {
        this(alias, aliased, null);
    }

    private DtField(Name alias, Table<DtFieldRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("字段信息"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.dt_field</code> table reference
     */
    public DtField(String alias) {
        this(DSL.name(alias), DT_FIELD);
    }

    /**
     * Create an aliased <code>public.dt_field</code> table reference
     */
    public DtField(Name alias) {
        this(alias, DT_FIELD);
    }

    /**
     * Create a <code>public.dt_field</code> table reference
     */
    public DtField() {
        this(DSL.name("dt_field"), null);
    }

    public <O extends Record> DtField(Table<O> child, ForeignKey<O, DtFieldRecord> key) {
        super(child, key, DT_FIELD);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DT_FIELD_APP_ID_INDEX, Indexes.DT_FIELD_TEMPLATE_ID_INDEX, Indexes.DT_FIELD_TENANT_ID_INDEX);
    }

    @Override
    public UniqueKey<DtFieldRecord> getPrimaryKey() {
        return Keys.DT_FIELD_PK;
    }

    @Override
    public DtField as(String alias) {
        return new DtField(DSL.name(alias), this);
    }

    @Override
    public DtField as(Name alias) {
        return new DtField(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DtField rename(String name) {
        return new DtField(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DtField rename(Name name) {
        return new DtField(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, LocalDateTime, LocalDateTime, Long, Long, String, String, String, JsonObject, Short, Long, Long, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
