/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository;


import com.datatable.repository.tables.DtApp;
import com.datatable.repository.tables.DtField;
import com.datatable.repository.tables.DtTemplate;
import com.datatable.repository.tables.DtUser;
import com.datatable.repository.tables.DtView;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DT_APP_TENANT_ID_INDEX = Internal.createIndex(DSL.name("dt_app_tenant_id_index"), DtApp.DT_APP, new OrderField[] { DtApp.DT_APP.TENANT_ID }, false);
    public static final Index DT_FIELD_APP_ID_INDEX = Internal.createIndex(DSL.name("dt_field_app_id_index"), DtField.DT_FIELD, new OrderField[] { DtField.DT_FIELD.APP_ID }, false);
    public static final Index DT_FIELD_TEMPLATE_ID_INDEX = Internal.createIndex(DSL.name("dt_field_template_id_index"), DtField.DT_FIELD, new OrderField[] { DtField.DT_FIELD.TEMPLATE_ID }, false);
    public static final Index DT_FIELD_TENANT_ID_INDEX = Internal.createIndex(DSL.name("dt_field_tenant_id_index"), DtField.DT_FIELD, new OrderField[] { DtField.DT_FIELD.TENANT_ID }, false);
    public static final Index DT_TEMPLATE_APP_ID_INDEX = Internal.createIndex(DSL.name("dt_template_app_id_index"), DtTemplate.DT_TEMPLATE, new OrderField[] { DtTemplate.DT_TEMPLATE.APP_ID }, false);
    public static final Index DT_TEMPLATE_TENANT_ID_INDEX = Internal.createIndex(DSL.name("dt_template_tenant_id_index"), DtTemplate.DT_TEMPLATE, new OrderField[] { DtTemplate.DT_TEMPLATE.TENANT_ID }, false);
    public static final Index DT_USER_APP_ID_INDEX = Internal.createIndex(DSL.name("dt_user_app_id_index"), DtUser.DT_USER, new OrderField[] { DtUser.DT_USER.APP_ID }, false);
    public static final Index DT_USER_TENANT_ID_INDEX = Internal.createIndex(DSL.name("dt_user_tenant_id_index"), DtUser.DT_USER, new OrderField[] { DtUser.DT_USER.TENANT_ID }, false);
    public static final Index DT_USER_USER_STATUS_INDEX = Internal.createIndex(DSL.name("dt_user_user_status_index"), DtUser.DT_USER, new OrderField[] { DtUser.DT_USER.USER_STATUS }, false);
    public static final Index DT_VIEW_APP_ID_INDEX = Internal.createIndex(DSL.name("dt_view_app_id_index"), DtView.DT_VIEW, new OrderField[] { DtView.DT_VIEW.APP_ID }, false);
    public static final Index DT_VIEW_TEMPLATE_ID_INDEX = Internal.createIndex(DSL.name("dt_view_template_id_index"), DtView.DT_VIEW, new OrderField[] { DtView.DT_VIEW.TEMPLATE_ID }, false);
    public static final Index DT_VIEW_TENANT_ID_INDEX = Internal.createIndex(DSL.name("dt_view_tenant_id_index"), DtView.DT_VIEW, new OrderField[] { DtView.DT_VIEW.TENANT_ID }, false);
}
