/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository;


import com.datatable.repository.tables.DtApp;
import com.datatable.repository.tables.DtField;
import com.datatable.repository.tables.DtTemplate;
import com.datatable.repository.tables.DtTenant;
import com.datatable.repository.tables.DtUser;
import com.datatable.repository.tables.DtView;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * app
     */
    public final DtApp DT_APP = DtApp.DT_APP;

    /**
     * 字段信息
     */
    public final DtField DT_FIELD = DtField.DT_FIELD;

    /**
     * 模版
     */
    public final DtTemplate DT_TEMPLATE = DtTemplate.DT_TEMPLATE;

    /**
     * 租户
     */
    public final DtTenant DT_TENANT = DtTenant.DT_TENANT;

    /**
     * 用户信息
     */
    public final DtUser DT_USER = DtUser.DT_USER;

    /**
     * 视图
     */
    public final DtView DT_VIEW = DtView.DT_VIEW;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DtApp.DT_APP,
            DtField.DT_FIELD,
            DtTemplate.DT_TEMPLATE,
            DtTenant.DT_TENANT,
            DtUser.DT_USER,
            DtView.DT_VIEW
        );
    }
}
