/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository;


import com.datatable.repository.tables.DtApp;
import com.datatable.repository.tables.DtField;
import com.datatable.repository.tables.DtTemplate;
import com.datatable.repository.tables.DtTenant;
import com.datatable.repository.tables.DtUser;
import com.datatable.repository.tables.DtView;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * app
     */
    public static final DtApp DT_APP = DtApp.DT_APP;

    /**
     * 字段信息
     */
    public static final DtField DT_FIELD = DtField.DT_FIELD;

    /**
     * 模版
     */
    public static final DtTemplate DT_TEMPLATE = DtTemplate.DT_TEMPLATE;

    /**
     * 租户
     */
    public static final DtTenant DT_TENANT = DtTenant.DT_TENANT;

    /**
     * 用户信息
     */
    public static final DtUser DT_USER = DtUser.DT_USER;

    /**
     * 视图
     */
    public static final DtView DT_VIEW = DtView.DT_VIEW;
}
