/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.interfaces;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * app
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDtApp extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.dt_app.id</code>.
     */
    public IDtApp setId(Long value);

    /**
     * Getter for <code>public.dt_app.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.dt_app.gmt_create</code>. 创建时间
     */
    public IDtApp setGmtCreate(LocalDateTime value);

    /**
     * Getter for <code>public.dt_app.gmt_create</code>. 创建时间
     */
    public LocalDateTime getGmtCreate();

    /**
     * Setter for <code>public.dt_app.gmt_modified</code>. 更新时间
     */
    public IDtApp setGmtModified(LocalDateTime value);

    /**
     * Getter for <code>public.dt_app.gmt_modified</code>. 更新时间
     */
    public LocalDateTime getGmtModified();

    /**
     * Setter for <code>public.dt_app.app_name</code>. 应用名称
     */
    public IDtApp setAppName(String value);

    /**
     * Getter for <code>public.dt_app.app_name</code>. 应用名称
     */
    public String getAppName();

    /**
     * Setter for <code>public.dt_app.app_desc</code>. 应用描述
     */
    public IDtApp setAppDesc(String value);

    /**
     * Getter for <code>public.dt_app.app_desc</code>. 应用描述
     */
    public String getAppDesc();

    /**
     * Setter for <code>public.dt_app.creator</code>. 创建人
     */
    public IDtApp setCreator(Long value);

    /**
     * Getter for <code>public.dt_app.creator</code>. 创建人
     */
    public Long getCreator();

    /**
     * Setter for <code>public.dt_app.editor</code>. 更新人
     */
    public IDtApp setEditor(Long value);

    /**
     * Getter for <code>public.dt_app.editor</code>. 更新人
     */
    public Long getEditor();

    /**
     * Setter for <code>public.dt_app.is_delete</code>. 0 否 1 是
     */
    public IDtApp setIsDelete(Short value);

    /**
     * Getter for <code>public.dt_app.is_delete</code>. 0 否 1 是
     */
    public Short getIsDelete();

    /**
     * Setter for <code>public.dt_app.tenant_id</code>. 租户id
     */
    public IDtApp setTenantId(Long value);

    /**
     * Getter for <code>public.dt_app.tenant_id</code>. 租户id
     */
    public Long getTenantId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IDtApp
     */
    public void from(IDtApp from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IDtApp
     */
    public <E extends IDtApp> E into(E into);

        @Override
        public default IDtApp fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setId,json::getLong,"id","java.lang.Long");
                setOrThrow(this::setGmtCreate,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"gmt_create","java.time.LocalDateTime");
                setOrThrow(this::setGmtModified,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"gmt_modified","java.time.LocalDateTime");
                setOrThrow(this::setAppName,json::getString,"app_name","java.lang.String");
                setOrThrow(this::setAppDesc,json::getString,"app_desc","java.lang.String");
                setOrThrow(this::setCreator,json::getLong,"creator","java.lang.Long");
                setOrThrow(this::setEditor,json::getLong,"editor","java.lang.Long");
                setOrThrow(this::setIsDelete,key -> {Integer i = json.getInteger(key); return i==null?null:i.shortValue();},"is_delete","java.lang.Short");
                setOrThrow(this::setTenantId,json::getLong,"tenant_id","java.lang.Long");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("id",getId());
                json.put("gmt_create",getGmtCreate()==null?null:getGmtCreate().toString());
                json.put("gmt_modified",getGmtModified()==null?null:getGmtModified().toString());
                json.put("app_name",getAppName());
                json.put("app_desc",getAppDesc());
                json.put("creator",getCreator());
                json.put("editor",getEditor());
                json.put("is_delete",getIsDelete());
                json.put("tenant_id",getTenantId());
                return json;
        }

}
