/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.interfaces;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 模版
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDtTemplate extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.dt_template.id</code>.
     */
    public IDtTemplate setId(Long value);

    /**
     * Getter for <code>public.dt_template.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.dt_template.gmt_create</code>. 创建时间
     */
    public IDtTemplate setGmtCreate(LocalDateTime value);

    /**
     * Getter for <code>public.dt_template.gmt_create</code>. 创建时间
     */
    public LocalDateTime getGmtCreate();

    /**
     * Setter for <code>public.dt_template.gmt_modified</code>. 修改时间
     */
    public IDtTemplate setGmtModified(LocalDateTime value);

    /**
     * Getter for <code>public.dt_template.gmt_modified</code>. 修改时间
     */
    public LocalDateTime getGmtModified();

    /**
     * Setter for <code>public.dt_template.creator</code>. 创建人
     */
    public IDtTemplate setCreator(Long value);

    /**
     * Getter for <code>public.dt_template.creator</code>. 创建人
     */
    public Long getCreator();

    /**
     * Setter for <code>public.dt_template.editor</code>. 更新人
     */
    public IDtTemplate setEditor(Long value);

    /**
     * Getter for <code>public.dt_template.editor</code>. 更新人
     */
    public Long getEditor();

    /**
     * Setter for <code>public.dt_template.template_name</code>.
     */
    public IDtTemplate setTemplateName(String value);

    /**
     * Getter for <code>public.dt_template.template_name</code>.
     */
    public String getTemplateName();

    /**
     * Setter for <code>public.dt_template.template_desc</code>. 描述
     */
    public IDtTemplate setTemplateDesc(String value);

    /**
     * Getter for <code>public.dt_template.template_desc</code>. 描述
     */
    public String getTemplateDesc();

    /**
     * Setter for <code>public.dt_template.tenant_id</code>.
     */
    public IDtTemplate setTenantId(Long value);

    /**
     * Getter for <code>public.dt_template.tenant_id</code>.
     */
    public Long getTenantId();

    /**
     * Setter for <code>public.dt_template.app_id</code>. 应用id
     */
    public IDtTemplate setAppId(Long value);

    /**
     * Getter for <code>public.dt_template.app_id</code>. 应用id
     */
    public Long getAppId();

    /**
     * Setter for <code>public.dt_template.is_delete</code>. 0 否 1 是
     */
    public IDtTemplate setIsDelete(Short value);

    /**
     * Getter for <code>public.dt_template.is_delete</code>. 0 否 1 是
     */
    public Short getIsDelete();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IDtTemplate
     */
    public void from(IDtTemplate from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IDtTemplate
     */
    public <E extends IDtTemplate> E into(E into);

        @Override
        public default IDtTemplate fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setId,json::getLong,"id","java.lang.Long");
                setOrThrow(this::setGmtCreate,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"gmt_create","java.time.LocalDateTime");
                setOrThrow(this::setGmtModified,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"gmt_modified","java.time.LocalDateTime");
                setOrThrow(this::setCreator,json::getLong,"creator","java.lang.Long");
                setOrThrow(this::setEditor,json::getLong,"editor","java.lang.Long");
                setOrThrow(this::setTemplateName,json::getString,"template_name","java.lang.String");
                setOrThrow(this::setTemplateDesc,json::getString,"template_desc","java.lang.String");
                setOrThrow(this::setTenantId,json::getLong,"tenant_id","java.lang.Long");
                setOrThrow(this::setAppId,json::getLong,"app_id","java.lang.Long");
                setOrThrow(this::setIsDelete,key -> {Integer i = json.getInteger(key); return i==null?null:i.shortValue();},"is_delete","java.lang.Short");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("id",getId());
                json.put("gmt_create",getGmtCreate()==null?null:getGmtCreate().toString());
                json.put("gmt_modified",getGmtModified()==null?null:getGmtModified().toString());
                json.put("creator",getCreator());
                json.put("editor",getEditor());
                json.put("template_name",getTemplateName());
                json.put("template_desc",getTemplateDesc());
                json.put("tenant_id",getTenantId());
                json.put("app_id",getAppId());
                json.put("is_delete",getIsDelete());
                return json;
        }

}
