/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.interfaces;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 租户
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDtTenant extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.dt_tenant.id</code>.
     */
    public IDtTenant setId(Long value);

    /**
     * Getter for <code>public.dt_tenant.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.dt_tenant.gmt_create</code>. 创建时间
     */
    public IDtTenant setGmtCreate(LocalDateTime value);

    /**
     * Getter for <code>public.dt_tenant.gmt_create</code>. 创建时间
     */
    public LocalDateTime getGmtCreate();

    /**
     * Setter for <code>public.dt_tenant.gmt_modified</code>. 修改时间
     */
    public IDtTenant setGmtModified(LocalDateTime value);

    /**
     * Getter for <code>public.dt_tenant.gmt_modified</code>. 修改时间
     */
    public LocalDateTime getGmtModified();

    /**
     * Setter for <code>public.dt_tenant.creator</code>. 创建人
     */
    public IDtTenant setCreator(Long value);

    /**
     * Getter for <code>public.dt_tenant.creator</code>. 创建人
     */
    public Long getCreator();

    /**
     * Setter for <code>public.dt_tenant.editor</code>. 更新人
     */
    public IDtTenant setEditor(Long value);

    /**
     * Getter for <code>public.dt_tenant.editor</code>. 更新人
     */
    public Long getEditor();

    /**
     * Setter for <code>public.dt_tenant.tenant_name</code>. 租户名称
     */
    public IDtTenant setTenantName(String value);

    /**
     * Getter for <code>public.dt_tenant.tenant_name</code>. 租户名称
     */
    public String getTenantName();

    /**
     * Setter for <code>public.dt_tenant.tenant_desc</code>. 租户描述
     */
    public IDtTenant setTenantDesc(String value);

    /**
     * Getter for <code>public.dt_tenant.tenant_desc</code>. 租户描述
     */
    public String getTenantDesc();

    /**
     * Setter for <code>public.dt_tenant.is_delete</code>. 0 否 1 是
     */
    public IDtTenant setIsDelete(Short value);

    /**
     * Getter for <code>public.dt_tenant.is_delete</code>. 0 否 1 是
     */
    public Short getIsDelete();

    /**
     * Setter for <code>public.dt_tenant.tenant_status</code>. 租户状态
     */
    public IDtTenant setTenantStatus(String value);

    /**
     * Getter for <code>public.dt_tenant.tenant_status</code>. 租户状态
     */
    public String getTenantStatus();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IDtTenant
     */
    public void from(IDtTenant from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IDtTenant
     */
    public <E extends IDtTenant> E into(E into);

        @Override
        public default IDtTenant fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setId,json::getLong,"id","java.lang.Long");
                setOrThrow(this::setGmtCreate,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"gmt_create","java.time.LocalDateTime");
                setOrThrow(this::setGmtModified,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"gmt_modified","java.time.LocalDateTime");
                setOrThrow(this::setCreator,json::getLong,"creator","java.lang.Long");
                setOrThrow(this::setEditor,json::getLong,"editor","java.lang.Long");
                setOrThrow(this::setTenantName,json::getString,"tenant_name","java.lang.String");
                setOrThrow(this::setTenantDesc,json::getString,"tenant_desc","java.lang.String");
                setOrThrow(this::setIsDelete,key -> {Integer i = json.getInteger(key); return i==null?null:i.shortValue();},"is_delete","java.lang.Short");
                setOrThrow(this::setTenantStatus,json::getString,"tenant_status","java.lang.String");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("id",getId());
                json.put("gmt_create",getGmtCreate()==null?null:getGmtCreate().toString());
                json.put("gmt_modified",getGmtModified()==null?null:getGmtModified().toString());
                json.put("creator",getCreator());
                json.put("editor",getEditor());
                json.put("tenant_name",getTenantName());
                json.put("tenant_desc",getTenantDesc());
                json.put("is_delete",getIsDelete());
                json.put("tenant_status",getTenantStatus());
                return json;
        }

}
