/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.interfaces;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;

import java.io.Serializable;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDtUser extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.dt_user.id</code>.
     */
    public IDtUser setId(Long value);

    /**
     * Getter for <code>public.dt_user.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.dt_user.gmt_create</code>. 创建时间
     */
    public IDtUser setGmtCreate(Long value);

    /**
     * Getter for <code>public.dt_user.gmt_create</code>. 创建时间
     */
    public Long getGmtCreate();

    /**
     * Setter for <code>public.dt_user.gmt_modified</code>. 修改时间
     */
    public IDtUser setGmtModified(Long value);

    /**
     * Getter for <code>public.dt_user.gmt_modified</code>. 修改时间
     */
    public Long getGmtModified();

    /**
     * Setter for <code>public.dt_user.user_name</code>. 用户名
     */
    public IDtUser setUserName(String value);

    /**
     * Getter for <code>public.dt_user.user_name</code>. 用户名
     */
    public String getUserName();

    /**
     * Setter for <code>public.dt_user.user_account</code>. 账号
     */
    public IDtUser setUserAccount(String value);

    /**
     * Getter for <code>public.dt_user.user_account</code>. 账号
     */
    public String getUserAccount();

    /**
     * Setter for <code>public.dt_user.user_password</code>. 密码
     */
    public IDtUser setUserPassword(String value);

    /**
     * Getter for <code>public.dt_user.user_password</code>. 密码
     */
    public String getUserPassword();

    /**
     * Setter for <code>public.dt_user.user_status</code>. 用户状态
     */
    public IDtUser setUserStatus(String value);

    /**
     * Getter for <code>public.dt_user.user_status</code>. 用户状态
     */
    public String getUserStatus();

    /**
     * Setter for <code>public.dt_user.is_delete</code>. 0 否 1 是
     */
    public IDtUser setIsDelete(Short value);

    /**
     * Getter for <code>public.dt_user.is_delete</code>. 0 否 1 是
     */
    public Short getIsDelete();

    /**
     * Setter for <code>public.dt_user.tenant_id</code>. 租户id
     */
    public IDtUser setTenantId(Long value);

    /**
     * Getter for <code>public.dt_user.tenant_id</code>. 租户id
     */
    public Long getTenantId();

    /**
     * Setter for <code>public.dt_user.app_id</code>. 应用id
     */
    public IDtUser setAppId(Long value);

    /**
     * Getter for <code>public.dt_user.app_id</code>. 应用id
     */
    public Long getAppId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IDtUser
     */
    public void from(IDtUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IDtUser
     */
    public <E extends IDtUser> E into(E into);

        @Override
        public default IDtUser fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setId,json::getLong,"id","java.lang.Long");
                setOrThrow(this::setGmtCreate,json::getLong,"gmt_create","java.lang.Long");
                setOrThrow(this::setGmtModified,json::getLong,"gmt_modified","java.lang.Long");
                setOrThrow(this::setUserName,json::getString,"user_name","java.lang.String");
                setOrThrow(this::setUserAccount,json::getString,"user_account","java.lang.String");
                setOrThrow(this::setUserPassword,json::getString,"user_password","java.lang.String");
                setOrThrow(this::setUserStatus,json::getString,"user_status","java.lang.String");
                setOrThrow(this::setIsDelete,key -> {Integer i = json.getInteger(key); return i==null?null:i.shortValue();},"is_delete","java.lang.Short");
                setOrThrow(this::setTenantId,json::getLong,"tenant_id","java.lang.Long");
                setOrThrow(this::setAppId,json::getLong,"app_id","java.lang.Long");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("id",getId());
                json.put("gmt_create",getGmtCreate());
                json.put("gmt_modified",getGmtModified());
                json.put("user_name",getUserName());
                json.put("user_account",getUserAccount());
                json.put("user_password",getUserPassword());
                json.put("user_status",getUserStatus());
                json.put("is_delete",getIsDelete());
                json.put("tenant_id",getTenantId());
                json.put("app_id",getAppId());
                return json;
        }

}
