/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.pojos;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;
import com.datatable.repository.tables.interfaces.IDtTenant;

import java.time.LocalDateTime;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 租户
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtTenant implements VertxPojo, IDtTenant {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime gmtCreate;
    private LocalDateTime gmtModified;
    private Long          creator;
    private Long          editor;
    private String        tenantName;
    private String        tenantDesc;
    private Short         isDelete;
    private String        tenantStatus;

    public DtTenant() {}

    public DtTenant(IDtTenant value) {
        this.id = value.getId();
        this.gmtCreate = value.getGmtCreate();
        this.gmtModified = value.getGmtModified();
        this.creator = value.getCreator();
        this.editor = value.getEditor();
        this.tenantName = value.getTenantName();
        this.tenantDesc = value.getTenantDesc();
        this.isDelete = value.getIsDelete();
        this.tenantStatus = value.getTenantStatus();
    }

    public DtTenant(
        Long          id,
        LocalDateTime gmtCreate,
        LocalDateTime gmtModified,
        Long          creator,
        Long          editor,
        String        tenantName,
        String        tenantDesc,
        Short         isDelete,
        String        tenantStatus
    ) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.creator = creator;
        this.editor = editor;
        this.tenantName = tenantName;
        this.tenantDesc = tenantDesc;
        this.isDelete = isDelete;
        this.tenantStatus = tenantStatus;
    }

        public DtTenant(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>public.dt_tenant.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.dt_tenant.id</code>.
     */
    @Override
    public DtTenant setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.dt_tenant.gmt_create</code>. 创建时间
     */
    @Override
    public LocalDateTime getGmtCreate() {
        return this.gmtCreate;
    }

    /**
     * Setter for <code>public.dt_tenant.gmt_create</code>. 创建时间
     */
    @Override
    public DtTenant setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
        return this;
    }

    /**
     * Getter for <code>public.dt_tenant.gmt_modified</code>. 修改时间
     */
    @Override
    public LocalDateTime getGmtModified() {
        return this.gmtModified;
    }

    /**
     * Setter for <code>public.dt_tenant.gmt_modified</code>. 修改时间
     */
    @Override
    public DtTenant setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
        return this;
    }

    /**
     * Getter for <code>public.dt_tenant.creator</code>. 创建人
     */
    @Override
    public Long getCreator() {
        return this.creator;
    }

    /**
     * Setter for <code>public.dt_tenant.creator</code>. 创建人
     */
    @Override
    public DtTenant setCreator(Long creator) {
        this.creator = creator;
        return this;
    }

    /**
     * Getter for <code>public.dt_tenant.editor</code>. 更新人
     */
    @Override
    public Long getEditor() {
        return this.editor;
    }

    /**
     * Setter for <code>public.dt_tenant.editor</code>. 更新人
     */
    @Override
    public DtTenant setEditor(Long editor) {
        this.editor = editor;
        return this;
    }

    /**
     * Getter for <code>public.dt_tenant.tenant_name</code>. 租户名称
     */
    @Override
    public String getTenantName() {
        return this.tenantName;
    }

    /**
     * Setter for <code>public.dt_tenant.tenant_name</code>. 租户名称
     */
    @Override
    public DtTenant setTenantName(String tenantName) {
        this.tenantName = tenantName;
        return this;
    }

    /**
     * Getter for <code>public.dt_tenant.tenant_desc</code>. 租户描述
     */
    @Override
    public String getTenantDesc() {
        return this.tenantDesc;
    }

    /**
     * Setter for <code>public.dt_tenant.tenant_desc</code>. 租户描述
     */
    @Override
    public DtTenant setTenantDesc(String tenantDesc) {
        this.tenantDesc = tenantDesc;
        return this;
    }

    /**
     * Getter for <code>public.dt_tenant.is_delete</code>. 0 否 1 是
     */
    @Override
    public Short getIsDelete() {
        return this.isDelete;
    }

    /**
     * Setter for <code>public.dt_tenant.is_delete</code>. 0 否 1 是
     */
    @Override
    public DtTenant setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
        return this;
    }

    /**
     * Getter for <code>public.dt_tenant.tenant_status</code>. 租户状态
     */
    @Override
    public String getTenantStatus() {
        return this.tenantStatus;
    }

    /**
     * Setter for <code>public.dt_tenant.tenant_status</code>. 租户状态
     */
    @Override
    public DtTenant setTenantStatus(String tenantStatus) {
        this.tenantStatus = tenantStatus;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DtTenant other = (DtTenant) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.gmtCreate == null) {
            if (other.gmtCreate != null)
                return false;
        }
        else if (!this.gmtCreate.equals(other.gmtCreate))
            return false;
        if (this.gmtModified == null) {
            if (other.gmtModified != null)
                return false;
        }
        else if (!this.gmtModified.equals(other.gmtModified))
            return false;
        if (this.creator == null) {
            if (other.creator != null)
                return false;
        }
        else if (!this.creator.equals(other.creator))
            return false;
        if (this.editor == null) {
            if (other.editor != null)
                return false;
        }
        else if (!this.editor.equals(other.editor))
            return false;
        if (this.tenantName == null) {
            if (other.tenantName != null)
                return false;
        }
        else if (!this.tenantName.equals(other.tenantName))
            return false;
        if (this.tenantDesc == null) {
            if (other.tenantDesc != null)
                return false;
        }
        else if (!this.tenantDesc.equals(other.tenantDesc))
            return false;
        if (this.isDelete == null) {
            if (other.isDelete != null)
                return false;
        }
        else if (!this.isDelete.equals(other.isDelete))
            return false;
        if (this.tenantStatus == null) {
            if (other.tenantStatus != null)
                return false;
        }
        else if (!this.tenantStatus.equals(other.tenantStatus))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.gmtCreate == null) ? 0 : this.gmtCreate.hashCode());
        result = prime * result + ((this.gmtModified == null) ? 0 : this.gmtModified.hashCode());
        result = prime * result + ((this.creator == null) ? 0 : this.creator.hashCode());
        result = prime * result + ((this.editor == null) ? 0 : this.editor.hashCode());
        result = prime * result + ((this.tenantName == null) ? 0 : this.tenantName.hashCode());
        result = prime * result + ((this.tenantDesc == null) ? 0 : this.tenantDesc.hashCode());
        result = prime * result + ((this.isDelete == null) ? 0 : this.isDelete.hashCode());
        result = prime * result + ((this.tenantStatus == null) ? 0 : this.tenantStatus.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DtTenant (");

        sb.append(id);
        sb.append(", ").append(gmtCreate);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(creator);
        sb.append(", ").append(editor);
        sb.append(", ").append(tenantName);
        sb.append(", ").append(tenantDesc);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(tenantStatus);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDtTenant from) {
        setId(from.getId());
        setGmtCreate(from.getGmtCreate());
        setGmtModified(from.getGmtModified());
        setCreator(from.getCreator());
        setEditor(from.getEditor());
        setTenantName(from.getTenantName());
        setTenantDesc(from.getTenantDesc());
        setIsDelete(from.getIsDelete());
        setTenantStatus(from.getTenantStatus());
    }

    @Override
    public <E extends IDtTenant> E into(E into) {
        into.from(this);
        return into;
    }
}
