/*
 * This file is generated by jOOQ.
 */
package com.datatable.repository.tables.pojos;


import com.datatable.framework.plugin.jooq.generate.VertxPojo;
import com.datatable.repository.tables.interfaces.IDtUser;


import static com.datatable.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtUser implements VertxPojo, IDtUser {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   gmtCreate;
    private Long   gmtModified;
    private String userName;
    private String userAccount;
    private String userPassword;
    private String userStatus;
    private Short  isDelete;
    private Long   tenantId;
    private Long   appId;

    public DtUser() {}

    public DtUser(IDtUser value) {
        this.id = value.getId();
        this.gmtCreate = value.getGmtCreate();
        this.gmtModified = value.getGmtModified();
        this.userName = value.getUserName();
        this.userAccount = value.getUserAccount();
        this.userPassword = value.getUserPassword();
        this.userStatus = value.getUserStatus();
        this.isDelete = value.getIsDelete();
        this.tenantId = value.getTenantId();
        this.appId = value.getAppId();
    }

    public DtUser(
        Long   id,
        Long   gmtCreate,
        Long   gmtModified,
        String userName,
        String userAccount,
        String userPassword,
        String userStatus,
        Short  isDelete,
        Long   tenantId,
        Long   appId
    ) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.userName = userName;
        this.userAccount = userAccount;
        this.userPassword = userPassword;
        this.userStatus = userStatus;
        this.isDelete = isDelete;
        this.tenantId = tenantId;
        this.appId = appId;
    }

        public DtUser(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>public.dt_user.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.dt_user.id</code>.
     */
    @Override
    public DtUser setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.gmt_create</code>. 创建时间
     */
    @Override
    public Long getGmtCreate() {
        return this.gmtCreate;
    }

    /**
     * Setter for <code>public.dt_user.gmt_create</code>. 创建时间
     */
    @Override
    public DtUser setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.gmt_modified</code>. 修改时间
     */
    @Override
    public Long getGmtModified() {
        return this.gmtModified;
    }

    /**
     * Setter for <code>public.dt_user.gmt_modified</code>. 修改时间
     */
    @Override
    public DtUser setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.user_name</code>. 用户名
     */
    @Override
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>public.dt_user.user_name</code>. 用户名
     */
    @Override
    public DtUser setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.user_account</code>. 账号
     */
    @Override
    public String getUserAccount() {
        return this.userAccount;
    }

    /**
     * Setter for <code>public.dt_user.user_account</code>. 账号
     */
    @Override
    public DtUser setUserAccount(String userAccount) {
        this.userAccount = userAccount;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.user_password</code>. 密码
     */
    @Override
    public String getUserPassword() {
        return this.userPassword;
    }

    /**
     * Setter for <code>public.dt_user.user_password</code>. 密码
     */
    @Override
    public DtUser setUserPassword(String userPassword) {
        this.userPassword = userPassword;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.user_status</code>. 用户状态
     */
    @Override
    public String getUserStatus() {
        return this.userStatus;
    }

    /**
     * Setter for <code>public.dt_user.user_status</code>. 用户状态
     */
    @Override
    public DtUser setUserStatus(String userStatus) {
        this.userStatus = userStatus;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.is_delete</code>. 0 否 1 是
     */
    @Override
    public Short getIsDelete() {
        return this.isDelete;
    }

    /**
     * Setter for <code>public.dt_user.is_delete</code>. 0 否 1 是
     */
    @Override
    public DtUser setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.tenant_id</code>. 租户id
     */
    @Override
    public Long getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.dt_user.tenant_id</code>. 租户id
     */
    @Override
    public DtUser setTenantId(Long tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * Getter for <code>public.dt_user.app_id</code>. 应用id
     */
    @Override
    public Long getAppId() {
        return this.appId;
    }

    /**
     * Setter for <code>public.dt_user.app_id</code>. 应用id
     */
    @Override
    public DtUser setAppId(Long appId) {
        this.appId = appId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DtUser other = (DtUser) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.gmtCreate == null) {
            if (other.gmtCreate != null)
                return false;
        }
        else if (!this.gmtCreate.equals(other.gmtCreate))
            return false;
        if (this.gmtModified == null) {
            if (other.gmtModified != null)
                return false;
        }
        else if (!this.gmtModified.equals(other.gmtModified))
            return false;
        if (this.userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!this.userName.equals(other.userName))
            return false;
        if (this.userAccount == null) {
            if (other.userAccount != null)
                return false;
        }
        else if (!this.userAccount.equals(other.userAccount))
            return false;
        if (this.userPassword == null) {
            if (other.userPassword != null)
                return false;
        }
        else if (!this.userPassword.equals(other.userPassword))
            return false;
        if (this.userStatus == null) {
            if (other.userStatus != null)
                return false;
        }
        else if (!this.userStatus.equals(other.userStatus))
            return false;
        if (this.isDelete == null) {
            if (other.isDelete != null)
                return false;
        }
        else if (!this.isDelete.equals(other.isDelete))
            return false;
        if (this.tenantId == null) {
            if (other.tenantId != null)
                return false;
        }
        else if (!this.tenantId.equals(other.tenantId))
            return false;
        if (this.appId == null) {
            if (other.appId != null)
                return false;
        }
        else if (!this.appId.equals(other.appId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.gmtCreate == null) ? 0 : this.gmtCreate.hashCode());
        result = prime * result + ((this.gmtModified == null) ? 0 : this.gmtModified.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.userAccount == null) ? 0 : this.userAccount.hashCode());
        result = prime * result + ((this.userPassword == null) ? 0 : this.userPassword.hashCode());
        result = prime * result + ((this.userStatus == null) ? 0 : this.userStatus.hashCode());
        result = prime * result + ((this.isDelete == null) ? 0 : this.isDelete.hashCode());
        result = prime * result + ((this.tenantId == null) ? 0 : this.tenantId.hashCode());
        result = prime * result + ((this.appId == null) ? 0 : this.appId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DtUser (");

        sb.append(id);
        sb.append(", ").append(gmtCreate);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(userName);
        sb.append(", ").append(userAccount);
        sb.append(", ").append(userPassword);
        sb.append(", ").append(userStatus);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(appId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDtUser from) {
        setId(from.getId());
        setGmtCreate(from.getGmtCreate());
        setGmtModified(from.getGmtModified());
        setUserName(from.getUserName());
        setUserAccount(from.getUserAccount());
        setUserPassword(from.getUserPassword());
        setUserStatus(from.getUserStatus());
        setIsDelete(from.getIsDelete());
        setTenantId(from.getTenantId());
        setAppId(from.getAppId());
    }

    @Override
    public <E extends IDtUser> E into(E into) {
        into.from(this);
        return into;
    }
}
