server:
  - name: coreHttp
    type: http
    config:
      port: 18080
      host: 192.168.0.39
      tcpKeepAlive: true
inject:
  jooq: com.datatable.framework.plugin.jooq.JooqInfix
#  redis: com.datacube.framework.plugin.redis.RedisInfix

cors:
  methods:
    - GET
    - POST
    - DELETE
    - PUT
    - PATCH
  headers:
    - x-requested-with
    - Access-Control-Allow-Origin
    - origin
    - Content-Type
    - accept
    - X-DataCube-Token

hazelcast:
  enabled: true
  clusterName: datatable

pg:
  host: 192.168.0.39
  port: 5432
  user: postgres
  password: '159357'
  database: data_table
  pool:
    maxSize: 10

datacube:
  clusteredSession: true
  sessionName: datatable-web.session

jooq:
  provider:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '159357'
    hostname: 192.168.0.39
    instance: data_table
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/data_table?useSSL=false
    category: POSTGRESQL

vertx:
  preferNativeTransport: true

flyway:
  url: jdbc:postgresql://127.0.0.1:5432/data_table?useSSL=false
  user: postgres
  password: '159357'
  locations: classpath:db/migration
  enable: true
  baselineOnMigrate: true
  baselineVersion: 0
  cleanDisabled: true